version: '3'

services:
  provider:
    image: dtr.rogfk.no/fint-beta/provider:1.3.6
    ports:
      - "8258:8080"
    environment:
      TZ: Europe/Oslo
      server.context-path: /utdanning/vurdering/provider
      fint.events.orgIds: "fint.health,rogfk.no,pwf.no,vsware.ie"
      fint.events.component: beta
      fint.events.env: beta
      fint.audit.mongo.hostname: 152.93.213.138
      fint.audit.mongo.databasename: fint-audit-beta
      fint.provider.sse-timeout-minutes: 19
      fint.hazelcast.members: consumer,provider
      endpoints.trace.sensitive: "false"
    deploy:
      placement:
        constraints:
          - node.role == worker
      replicas: 1
      restart_policy:
        condition: on-failure
        delay: 5s
        max_attempts: 3
        window: 120s

  consumer:
    image: dtr.rogfk.no/fint-beta/consumer-utdanning-vurdering:0.0.0-2.6.0
    ports:
      - "8259:8080"
    environment:
      TZ: Europe/Oslo
      server.context-path: /utdanning/vurdering
      fint.events.orgIds: "fint.health,rogfk.no,pwf.no,vsware.ie"
      fint.events.component: beta
      fint.events.env: beta
      fint.relations.default-base-url: "https://beta.felleskomponent.no"
      fint.audit.mongo.hostname: 152.93.213.138
      fint.audit.mongo.databasename: fint-audit-beta
      fint.hazelcast.members: consumer,provider
      fint.cache.manager: hazelcast
    deploy:
      placement:
        constraints:
          - node.role == worker
      replicas: 1
      restart_policy:
        condition: on-failure
        delay: 5s
        max_attempts: 3
        window: 120s

  health-adapter:
    image: fint/health-adapter:latest
    environment:
      TZ: Europe/Oslo
      springfox.title: "Health Adapter"
      fint.adapter.organizations: fint.health
      fint.adapter.sse-endpoint: http://provider:8080/utdanning/vurdering/provider/sse/%s
      fint.adapter.status-endpoint: http://provider:8080/utdanning/vurdering/provider/status
      fint.adapter.response-endpoint: http://provider:8080/utdanning/vurdering/provider/response
    deploy:
      placement:
        constraints:
          - node.role == worker
      replicas: 1
      restart_policy:
        condition: on-failure
        delay: 5s
        max_attempts: 3
        window: 120s
