name: Publish to Azure Container Registry

on:
  release:
    types: [ published ]

env:
  REGISTRY_NAME: fintlabsacr

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Set environment variables
        run: |
          echo "REPO_NAME=${GITHUB_REPOSITORY#*/}" >> $GITHUB_ENV
          echo "RELEASE_VERSION=${TAG_NAME:1}" >> $GITHUB_ENV
        env: 
          TAG_NAME: ${{github.event.release.tag_name}}

      - name: Connect to Azure Container Registry (ACR)
        uses: azure/docker-login@v1
        with:
          login-server: ${{env.REGISTRY_NAME}}.azurecr.io
          username: ${{secrets.REGISTRY_USERNAME}}
          password: ${{secrets.REGISTRY_PASSWORD}}

      - name: Container build and push to a Azure Container Registry (ACR)
        run: |
          API_VERSION=`cat gradle.properties | grep apiVersion | cut -d'=' -f2`
          echo Current API version is $API_VERSION
          docker build . -t ${{env.REGISTRY_NAME}}.azurecr.io/${{env.REPO_NAME}}:${{env.RELEASE_VERSION}} --build-arg apiVersion=$API_VERSION
          docker push ${{env.REGISTRY_NAME}}.azurecr.io/${{env.REPO_NAME}}:${{env.RELEASE_VERSION}}